services:
  saludo:
    build: ./saludo
    ports:
      - "80:80"
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_EXP=${TOKEN_EXP}
    restart: unless-stopped

  auth:
    build: ./auth
    ports:
      - "90:90"
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_EXP=${TOKEN_EXP}
    restart: unless-stopped

  cliente:
    build: ./client
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - AUTH_URL=http://auth:90/auth/login
      - SALUDO_URL=http://saludo/saludo
    restart: unless-stopped
