# Imagen base de Node
FROM node:18

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el archivo index.js
COPY /app/index.js .

# Comando para ejecutar el programa
CMD ["node", "index.js"]
